trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - '**/README.md'

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: liam-goodchild/pipeline-engineering-templates
      endpoint: liam-goodchild
      ref: refs/heads/main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: prd
  - name: additionalTfVars
    displayName: Additional Terraform Variables
    type: string
    default: ' '
  - name: enableVersioning
    displayName: Enable Git Versioning
    type: boolean
    default: true
  - name: envs
    type: object
    default:
      prd:
        backendResourceGroupName: sh-mgmt-prd-uks-tf-rg-01
        backendStorageAccountName: shmgmtprdukstfst01
        tfvars: infra/vars/uks/prd.tfvars
        staticWebAppName: sh-app-prd-uks-cve-stapp-01
        resourceGroupName: sh-app-prd-uks-cve-rg-01

variables:
  backendContainerName: solution-cvengine-core
  serviceConnectionName: sh-sc-cvengine
  globalTfvars: infra/vars/globals.tfvars
  backendResourceGroupName: ${{ parameters.envs[parameters.environment].backendResourceGroupName }}
  backendStorageAccountName: ${{ parameters.envs[parameters.environment].backendStorageAccountName }}
  tfvars: ${{ parameters.envs[parameters.environment].tfvars }}
  staticWebAppName: ${{ parameters.envs[parameters.environment].staticWebAppName }}
  resourceGroupName: ${{ parameters.envs[parameters.environment].resourceGroupName }}

stages:
  # Stage 1: Terraform Plan
  - stage: Plan
    displayName: 'Terraform Plan'
    jobs:
      - job: TerraformPlan
        displayName: 'Terraform Plan'
        steps:
          - checkout: self
          - template: terraform/terraform-cicd.yaml@templates
            parameters:
              terraformAction: plan
              serviceConnectionName: $(serviceConnectionName)
              backendResourceGroupName: $(backendResourceGroupName)
              backendStorageAccountName: $(backendStorageAccountName)
              backendContainerName: $(backendContainerName)
              backendKey: terraform.tfstate
              envTfvars: $(tfvars)
              globalTfvars: $(globalTfvars)
              additionalCommandOptions: ${{ parameters.additionalTfVars }}
              publishPlan: true
              planArtifactName: 'tfplan-${{ parameters.environment }}'
              ensureBackendContainer: true

  # Stage 2: Terraform Apply
  - stage: Apply
    displayName: 'Terraform Apply'
    dependsOn: Plan
    condition: succeeded()
    jobs:
      - job: TerraformApply
        displayName: 'Terraform Apply'
        steps:
          - checkout: self
          - template: terraform/terraform-cicd.yaml@templates
            parameters:
              terraformAction: apply
              serviceConnectionName: $(serviceConnectionName)
              backendResourceGroupName: $(backendResourceGroupName)
              backendStorageAccountName: $(backendStorageAccountName)
              backendContainerName: $(backendContainerName)
              backendKey: terraform.tfstate
              envTfvars: $(tfvars)
              globalTfvars: $(globalTfvars)
              additionalCommandOptions: ${{ parameters.additionalTfVars }}
              ensureBackendContainer: false

  # Stage 3: Deploy Static Web App
  - stage: SWA_Deploy
    displayName: 'Deploy Static Web App'
    dependsOn: Apply
    condition: succeeded()
    jobs:
      - job: SWA_Deploy
        displayName: 'Deploy Static Web App Content'
        steps:
          - checkout: self

          - task: NodeTool@0
            displayName: 'Select Node Version'
            inputs:
              versionSpec: '18.x'

          - script: |
              set -euo pipefail
              cd functions
              npm install
              npm run build --if-present
            displayName: 'Build Functions'

          - task: AzureCLI@2
            displayName: 'Get SWA Deployment Token'
            inputs:
              azureSubscription: $(serviceConnectionName)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -euo pipefail
                TOKEN=$(az staticwebapp secrets list \
                  --name "$(staticWebAppName)" \
                  --resource-group "$(resourceGroupName)" \
                  --query "properties.apiKey" -o tsv)
                echo "##vso[task.setvariable variable=SWA_DEPLOYMENT_TOKEN;issecret=true]$TOKEN"

          - task: AzureStaticWebApp@0
            displayName: 'Deploy to Static Web App'
            inputs:
              app_location: 'frontend'
              api_location: 'functions'
              output_location: ''
              azure_static_web_apps_api_token: $(SWA_DEPLOYMENT_TOKEN)

  # Stage 4: Git Versioning
  - stage: Versioning
    displayName: 'Git Versioning'
    dependsOn: SWA_Deploy
    condition: and(succeeded(), eq('${{ parameters.enableVersioning }}', 'true'))
    jobs:
      - job: GitVersioning
        displayName: 'Create Git Tag'
        steps:
          - template: versioning/git-versioning.yaml@templates
            parameters:
              defaultAction: patch
              defaultBranch: main
