trigger: none
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: liam-goodchild/pipeline-engineering-templates
      endpoint: liam-goodchild
      ref: refs/heads/main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: terraformAction
    displayName: Terraform Action
    type: string
    default: Plan
    values: [Plan, Apply, Destroy]
  - name: environment
    displayName: Environment
    type: string
    default: dev
    values: [dev, prd]
  - name: additionalTfVars
    displayName: Additional Terraform Variables
    type: string
    default: ' '
  - name: envs
    type: object
    default:
      dev:
        backendResourceGroupName: sh-mgmt-dev-uks-tf-rg-01
        backendStorageAccountName: shmgmtdevukstfst01
        tfvars: infra/vars/uks/dev.tfvars
        staticWebAppName: sh-app-dev-uks-cve-stapp-01
        resourceGroupName: sh-app-dev-uks-cve-rg-01
      prd:
        backendResourceGroupName: sh-mgmt-prd-uks-tf-rg-01
        backendStorageAccountName: shmgmtprdukstfst01
        tfvars: infra/vars/uks/prd.tfvars
        staticWebAppName: sh-app-prd-uks-cve-stapp-01
        resourceGroupName: sh-app-prd-uks-cve-rg-01

variables:
  backendContainerName: solution-cvengine-core
  serviceConnectionName: sh-sc-cvengine
  globalTfvars: infra/vars/globals.tfvars
  backendResourceGroupName: ${{ parameters.envs[parameters.environment].backendResourceGroupName }}
  backendStorageAccountName: ${{ parameters.envs[parameters.environment].backendStorageAccountName }}
  tfvars: ${{ parameters.envs[parameters.environment].tfvars }}
  staticWebAppName: ${{ parameters.envs[parameters.environment].staticWebAppName }}
  resourceGroupName: ${{ parameters.envs[parameters.environment].resourceGroupName }}

stages:
  # Terraform Plan
  - ${{ if eq(parameters.terraformAction, 'Plan') }}:
      - stage: Plan
        displayName: 'Terraform Plan'
        jobs:
          - job: TerraformPlan
            displayName: 'Terraform Plan'
            steps:
              - checkout: self
              - template: terraform/terraform-dev.yaml@templates
                parameters:
                  terraformAction: plan
                  serviceConnectionName: $(serviceConnectionName)
                  backendResourceGroupName: $(backendResourceGroupName)
                  backendStorageAccountName: $(backendStorageAccountName)
                  backendContainerName: $(backendContainerName)
                  backendKey: terraform.tfstate
                  envTfvars: $(tfvars)
                  globalTfvars: $(globalTfvars)
                  additionalCommandOptions: ${{ parameters.additionalTfVars }}

  # Terraform Apply
  - ${{ if eq(parameters.terraformAction, 'Apply') }}:
      - stage: Apply
        displayName: 'Terraform Apply'
        jobs:
          - job: TerraformApply
            displayName: 'Terraform Apply'
            steps:
              - checkout: self
              - template: terraform/terraform-dev.yaml@templates
                parameters:
                  terraformAction: apply
                  serviceConnectionName: $(serviceConnectionName)
                  backendResourceGroupName: $(backendResourceGroupName)
                  backendStorageAccountName: $(backendStorageAccountName)
                  backendContainerName: $(backendContainerName)
                  backendKey: terraform.tfstate
                  envTfvars: $(tfvars)
                  globalTfvars: $(globalTfvars)
                  additionalCommandOptions: ${{ parameters.additionalTfVars }}

      - stage: SWA_Deploy
        displayName: 'Deploy Static Web App'
        dependsOn: Apply
        condition: succeeded()
        jobs:
          - job: SWA_Deploy
            displayName: 'Deploy Static Web App Content'
            steps:
              - checkout: self

              - task: NodeTool@0
                displayName: 'Select Node Version'
                inputs:
                  versionSpec: '18.x'

              - script: |
                  set -euo pipefail
                  cd functions
                  npm install
                  npm run build --if-present
                displayName: 'Build Functions'

              - task: AzureCLI@2
                displayName: 'Get SWA Deployment Token'
                inputs:
                  azureSubscription: $(serviceConnectionName)
                  scriptType: bash
                  scriptLocation: inlineScript
                  inlineScript: |
                    set -euo pipefail
                    TOKEN=$(az staticwebapp secrets list \
                      --name "$(staticWebAppName)" \
                      --resource-group "$(resourceGroupName)" \
                      --query "properties.apiKey" -o tsv)
                    echo "##vso[task.setvariable variable=SWA_DEPLOYMENT_TOKEN;issecret=true]$TOKEN"

              - task: AzureStaticWebApp@0
                displayName: 'Deploy to Static Web App'
                inputs:
                  app_location: 'frontend'
                  api_location: 'functions'
                  output_location: ''
                  azure_static_web_apps_api_token: $(SWA_DEPLOYMENT_TOKEN)

  # Terraform Destroy
  - ${{ if eq(parameters.terraformAction, 'Destroy') }}:
      - stage: Destroy
        displayName: 'Terraform Destroy'
        jobs:
          - job: TerraformDestroy
            displayName: 'Terraform Destroy'
            steps:
              - checkout: self
              - template: terraform/terraform-dev.yaml@templates
                parameters:
                  terraformAction: destroy
                  serviceConnectionName: $(serviceConnectionName)
                  backendResourceGroupName: $(backendResourceGroupName)
                  backendStorageAccountName: $(backendStorageAccountName)
                  backendContainerName: $(backendContainerName)
                  backendKey: terraform.tfstate
                  envTfvars: $(tfvars)
                  globalTfvars: $(globalTfvars)
                  additionalCommandOptions: ${{ parameters.additionalTfVars }}
